services:
  stable-diffusion-webui:
    container_name: stable-diffusion-webui
    image: sd-webui:latest
    environment:
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ./models:/stable-diffusion-webui/models
      - ./outputs:/stable-diffusion-webui/outputs
    environment:
      CLI_ARGS: "--skip-version-check --allow-code --enable-insecure-extension-access --api --xformers --opt-channelslast"
    ports:
      - "7860:7860"    
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]